const Object = [
  {
    id: 1,
    avatar: 'https://miro.medium.com/fit/c/72/72/1*_q-PU7xK57PxME6XCRWbaA.png',
    name: 'Jari Roomer',
    day: 'May 4',
    title: '10 Things To Do Instead of Scrolling Through Your Smartphone',
    desc: '“Don’t become a slave to technology — manage your phone, don’t let it manage you.” — As Richard Branson said, “Don’t become a slave to',
    img: 'https://miro.medium.com/fit/c/140/140/0*q-4W7FkbMVg8Fner',
    type: 'Productivity',
    time: '6 min read',
    select: 'Selected for you',
  },
  {
    id: 2,
    avatar: 'https://miro.medium.com/fit/c/30/30/0*1_laT8QNC5bWHpSu',
    name: 'Sandy Kesuma Putra',
    day: 'Mar 31',
    title: 'Case Study: Gojek App Redesign',
    desc: 'Introduction Hello! My name is Sandy Kesuma Putra, I am a final year student majoring in product design at telkom university. In the last few months, I have participated in a UI/UX design boot camp held by',
    img: 'https://miro.medium.com/fit/c/140/140/1*fovkC-Eb6_TCof1qt6Is3Q.jpeg',
    type: 'UI',
    time: '8 min read',
    select: 'Selected for you'
  },
  {
    id: 3,
    avatar: 'https://miro.medium.com/fit/c/30/30/1*QDJsKs7OV9h6R5aaMJaOFQ.png',
    name: 'Henrik Larsen Toft in Level Up Coding',
    day: '5 days ago',
    title: '5 Advanced JavaScript concepts that will make you a better developer',
    desc: '5 Advanced JavaScript concepts that will make you a better developer',
    img: ' https://miro.medium.com/fit/c/140/140/0*1V1IqXmsODAvF4vo',
    type: 'JavaScript',
    time: '3 min read',
    select: 'Selected for you'
  },
  {
    id: 4,
    avatar: 'https://miro.medium.com/fit/c/30/30/1*vgGmI6c8XaCXHcm2LLOXVQ.png',
    name: 'Gustave Deresse in Ten Headlines',
    day: '20 hours ago',
    title: 'with Gustave Deresse — Éoh!! How are you? I have your headlines right here, if you want to check them out. Let me know what you think. I’m wondering if the silliness to you is a good or a bad thing. Or do you think I',
    desc: '5 Advanced JavaScript concepts that will make you a better developer',
    img: 'https://miro.medium.com/fit/c/140/140/0*8pW4xN7OvNsjq7Ib',
    type: 'Headlines',
    time: '2 min read',
    select: 'Selected for you'
  },
  {
    id: 5,
    avatar: 'https://miro.medium.com/fit/c/30/30/1*u9eo4N8MufxBkYWK7GnVBg@2x.jpeg',
    name: 'Rebecca Stevens A. in ILLUMINATION-Curated',
    day: 'Jan 24',
    title: '6 Ways A Black Person Can Tell A White Person Isn’t Racist',
    desc: 'It’s not that complicated — Black people can detect racists from a mile off. It’s the way they look at us — it’s often a look of disgust, deep hatred, or',
    type: 'Design',
    img: 'https://miro.medium.com/fit/c/140/140/0*WqGxaVmPLlORFNDf',
    time: '4 min read',
    select: 'Selected for you'
  },
  {
    id: 6,
    avatar: 'https://miro.medium.com/fit/c/30/30/1*2uZNASNFjSVqQxmFlE5yvA.jpeg',
    name: 'Codeart',
    day: 'Updated Jan 26',
    title: 'UI/UX Design Trends of 2022',
    desc: 'As 2021 is coming to a close, we are taking the time to review some of the most notable trends for the upcoming year. These past couple of years serve as particularly strong evidence of the constant and fast development',
    img: 'https://miro.medium.com/fit/c/140/140/1*gfQL8iTqOKozDq10UZ_xxQ.jpeg',
    type: 'Design',
    time: '7 min read',
    select: 'Selected for you'
  },
  {
    id: 7,
    avatar: 'https://miro.medium.com/fit/c/30/30/1*GhBBsOPuKkwpNniGdJP-Zw.jpeg',
    name: 'Nimit Sharma',
    day: '6 days ago',
    title: '4 Laws of Atomic Habits That Will Change Your Life',
    desc: 'Making a habit of exercising, making your children eat their vegetables, or sticking to your New Year’s resolutions — it can all seem so difficult sometimes. But if you want to change your life and make better habits stic',
    img: 'https://miro.medium.com/fit/c/140/140/1*gyfhnyMF9Bv8mzNu9uClsg.jpeg',
    type: 'Relationships',
    time: '5 min read',
    select: 'Selected for you'
  },
  {
    id: 8,
    avatar: 'https://miro.medium.com/fit/c/30/30/1*udF78cn1n9q1hCqW8T5hnQ.jpeg',
    name: 'Darshak Rana in Better Humans',
    day: 'Apr 25',
    title: '5 Gaslighting Phrases People Casually Use To Manipulate You',
    desc: 'Watch out for these signs and phrases to protect yourselves from mental abuse — What comes to your mind when you think of the word',
    img: 'https://miro.medium.com/fit/c/140/140/0*I3fFKzJnbaKfl8To',
    type: 'Relationships',
    time: '6 min read',
    select: 'Selected for you'
  },
  {
    id: 9,
    avatar: 'https://miro.medium.com/fit/c/30/30/0*mpQ4KW98NCEEDsOr',
    name: 'Hemant Tulsan',
    day: '2 days ago',
    title: 'Why I will never forget 25th May’22?',
    desc: 'This is my story of heartbreak and realisations :) Imagine getting rejected by all the places you wanted to be. I wasn’t even waitlisted. It shook me up, am I not even worthy of waitlist consideration? Hi, my name is Hemant, I',
    img: 'https://miro.medium.com/fit/c/140/140/1*EIqZtGgfbjRxBTdJdB85Ig.jpeg',
    type: 'JavaScript',
    time: '4 min read',
    select: 'Selected for you'
  },
  {
    id: 10,
    avatar: 'https://miro.medium.com/fit/c/30/30/2*4iq0kQ5lbLsLRJbrJyqPmA.jpeg',
    name: 'Jesse Choi in Going Southeast',
    day: 'Feb 9',
    title: 'Moving to Jakarta Part 1: The Why',
    desc: 'Here’s a quick update on the latest chapter of my life! — I moved to Jakarta, Indonesia exactly four months ago. This is a view of a particularly dramatic sunset from my apartment window. My phone doesn’t do it justice, but',
    img: 'https://miro.medium.com/fit/c/140/140/1*UHEoCgyE0O1B0-fveWY1_g.png',
    type: 'UI',
    time: '7 min read',
    select: 'Selected for you'
  },
];

export default Object;